### PR TITLE
add "Add Selection for Next Occurence" and "Unselect Occurence"

### PR DESCRIPTION
**Pull request by christophehurpeau**

### CODE REVIEW

**Comment by guylabs** [comment]
Hi @christophehurpeau,

thanks a lot for your contribution! Do you use a Mac or Windows/Linux? As the shortcuts for the Mac would be `CMD+G` and `CMD+SHIFT+G`. In the official keymap it is called `Find next` and `Find previous`. Could you maybe change this and also add it for Windows if you have the possibility? If not I will try to add it such that the shortcuts are consistent over the operating systems.

Thanks and regards,

Guy

**Comment by christophehurpeau** [comment]
[Yes, for mac, Select next occurence is Ctrl+G and for Windows/Linux it's Alt+J](http://blog.jetbrains.com/idea/2014/03/intellij-idea-13-1-rc-introduces-sublime-text-style-multiple-selections/)
I added the shortcuts for Windows/Linux

**Comment by guylabs** [comment]
Hi @christophehurpeau,

thanks a lot for your contribution! And sorry for the delay but I couldn't have a look at it earlier. I will merge it to master, add you as contributor and then release a new version later this week.

Thanks and regards,

Guy

**Comment by guylabs** [comment]
I just released https://github.com/guylabs/intellij-idea-keymap/releases/tag/v0.2.1 with your changes.

**Comment by christophehurpeau** [comment]
Thanks :)

**Pull request merged**
